### ISSUE TITLE
Insufficient maximum limit of Texture Layers

### ISSUE THREAD

**Issue by GeraldKimmersdorfer** [weBIGeo/webigeo#17]
The device limits for the `maxTextureArrayLayers` in Chromium are too small. The tiered device limits in DAWN seem to need an update to allow for more than 256 texture layers.

Bug-Report for the DAWN-project was issued as proposed in the dawn matrix chatroom: https://bugs.chromium.org/p/dawn/issues/detail?id=2558

**Comment by pkomon-tgm** [comment]
As mentioned in comment https://issues.chromium.org/issues/42241514#comment5, they fixed it in commit https://dawn.googlesource.com/dawn.git/+log/4975e45e9480..bcac5f764a1a.

This has already been merged into main and is already available in Chrome's release channel for nightly build (called Google Chrome Canary).

I can confirm the higher limit is available on my device with Google Chrome Canary 126.0.6462.0 🥳

**Comment by GeraldKimmersdorfer** [comment]
The Stable Chrome build is now on 6533. This issue can be closed.
