### ISSUE TITLE
Blackscreen after using scroll wheel in web

### ISSUE THREAD

**Issue by pkomon-tgm** [weBIGeo/webigeo#24]
Using the scroll wheel without other prior interaction in the web version causes a black screen, that can only be fixed by reloading the page.

To reproduce

1. host WASM build (debug) locally
2. open page in Chrome, wait until terrain has loaded and app has become responsive
3. scroll input (direction irrelevant)
4. blackscreen, imgui overlay still visible

This might have something to do with depth buffer read back. 
The issue does not appear the mouse is pressed down first. Maybe some initializiation is missing somewhere.

tested on Google Chrome 127.0.6533.73

**Comment by GeraldKimmersdorfer** [comment]
Our input mapping used the last mouse position. But this was not initialized as now we only send mouse move events when a button is pressed.

I now query the mouse position with `glfwGetCursorPos` on scroll.

fixed with 8b90acb54a2c2040781e2bcd400ad751d9a1008a
