### ISSUE TITLE
Multithreading in WASM build

### ISSUE THREAD

**Issue by GeraldKimmersdorfer** [weBIGeo/webigeo#28]
Multithreading in the Web would decrease the stuttering. Given the high requirements for weBIGeo to run, it can probably be the default configuration. (Some browsers don't like it) The following steps may be necessary:
- [x] Recompile custom emscripten qt binaries with appropriate flag
- [x] Activate `ALP_ENABLE_THREADING' flag and make sure that the webworker js file is properly build

**Comment by pkomon-tgm** [comment]
Implemented in fdc6be87c4b069e6082fbcbd94e88b2627e0a7d5.
Added setup instructions in README (+ workaround mentioned in https://github.com/emscripten-core/emscripten/issues/21844)
